const pruebaRecipes = [
    {
        id: '149',
        name: 'Pizza',
        healthScore: '75',
        createdInDB: true,
        banned: false,
        user_id: '1',
    },
    {
        id: '155',
        name: 'Pasta al pesto',
        healthScore: '85',
        createdInDB: true,
        banned: false,
        user_id: '1',
    },
    {
        id: '247',
        name: 'asado a las brazas',
        healthScore: '78',
        createdInDB: true,
        banned: false,
        user_id: '5',
    },
    {
        id: '146',
        name: 'Sopa de verduras',
        healthScore: '95',
        createdInDB: false,
        banned: true,
        user_id: 'Null',
    },
    {
        id: '169',
        name: 'Maccaoroni',
        healthScore: '85',
        createdInDB: false,
        banned: false,
        user_id: 'Null',
    },
    {
        id: '19',
        name: 'Ensalada de frutas',
        healthScore: '89',
        createdInDB: true,
        banned: false,
        user_id: '33',
    },
    {
        id: '166',
        name: 'Sarazza al disco',
        healthScore: '72',
        createdInDB: true,
        banned: false,
        user_id: '31',
    },
    {
        id: '49',
        name: 'Ensalada Ceasar',
        healthScore: '83',
        createdInDB: true,
        banned: false,
        user_id: '21',
    },
    {
        id: '38',
        name: 'Locro',
        healthScore: '75',
        createdInDB: false,
        banned: true,
        user_id: 'Null',
    },
    {
        id: '177',
        name: 'Pozole',
        healthScore: '99',
        createdInDB: true,
        banned: false,
        user_id: '1',
    },
    {
        id: '143',
        name: 'Mole Poblano',
        healthScore: '66',
        createdInDB: false,
        banned: false,
        user_id: 'Null',
    },
    {
        id: '49',
        name: 'tallarines con salsa de tomate',
        healthScore: '77',
        createdInDB: true,
        banned: true,
        user_id: '11',
    },
    {
        id: '137',
        name: 'lomo saltado',
        healthScore: '72',
        createdInDB: false,
        banned: false,
        user_id: 'Null',
    },
    {
        id: '109',
        name: 'Arroz con pollo',
        healthScore: '73',
        createdInDB: true,
        banned: false,
        user_id: '22',
    },
]

export default pruebaRecipes