const pruebaUsers = [
    {
        id: '1',
        username: 'Juan',
        email: 'juan@email.com',
        password: '123456',
        banned: false,
        admin: false,
        premium: true,
        nutricionist: false,
        free: false,
        logged: true,
    },
    {
        id: '2',
        username: 'Pedro',
        email: 'pedro@email.com',
        password: '144456',
        banned: true,
        admin: false,
        premium: false,
        nutricionist: true,
        free: false,
        logged: false,
    },
    {
        id: '3',
        username: 'Tito',
        email: 'tito@email.com',
        password: '744455',
        banned: false,
        admin: true,
        premium: false,
        nutricionist: false,
        free: false,
        logged: false,
    },
    {
        id: '4',
        username: 'Toto',
        email: 'toto@email.com',
        password: '743355',
        banned: false,
        admin: false,
        premium: false,
        nutricionist: false,
        free: true,
        logged: true,
    },
    {
        id: '5',
        username: 'Hugo',
        email: 'hugo@email.com',
        password: '943355',
        banned: true,
        admin: false,
        premium: false,
        nutricionist: false,
        free: true,
        logged: false,
    },
    {
        id: '6',
        username: 'Juanito',
        email: 'juanito@email.com',
        password: '123456',
        banned: false,
        admin: false,
        premium: true,
        nutricionist: false,
        free: false,
        logged: true,
    },
    {
        id: '7',
        username: 'Pedrovich',
        email: 'pedrov@email.com',
        password: '144456',
        banned: true,
        admin: false,
        premium: false,
        nutricionist: true,
        free: false,
        logged: false,
    },
    {
        id: '8',
        username: 'Titon',
        email: 'titon@email.com',
        password: '744455',
        banned: false,
        admin: true,
        premium: false,
        nutricionist: false,
        free: false,
        logged: false,
    },
    {
        id: '9',
        username: 'Totoloco',
        email: 'totol@email.com',
        password: '743355',
        banned: false,
        admin: false,
        premium: false,
        nutricionist: false,
        free: true,
        logged: true,
    },
    {
        id: '10',
        username: 'Hugovius',
        email: 'hugov@email.com',
        password: '943355',
        banned: true,
        admin: false,
        premium: false,
        nutricionist: false,
        free: true,
        logged: false,
    },
    {
        id: '11',
        username: 'Titonegro',
        email: 'titon@email.com',
        password: '744455',
        banned: false,
        admin: true,
        premium: false,
        nutricionist: false,
        free: false,
        logged: false,
    },
    {
        id: '12',
        username: 'Totololo',
        email: 'totol@email.com',
        password: '743355',
        banned: false,
        admin: false,
        premium: false,
        nutricionist: false,
        free: true,
        logged: true,
    },
    {
        id: '13',
        username: 'Hugon',
        email: 'hugov@email.com',
        password: '943355',
        banned: true,
        admin: false,
        premium: false,
        nutricionist: false,
        free: true,
        logged: false,
    }
]

export default pruebaUsers